const API="https://api.dictionaryapi.dev/api/v2/entries/en/";
const state={user:JSON.parse(localStorage.getItem("lexivn_user")||"null"),favorites:JSON.parse(localStorage.getItem("lexivn_favorites")||"[]"),history:JSON.parse(localStorage.getItem("lexivn_history")||"[]"),theme:localStorage.getItem("lexivn_theme")||"light"};
const app=document.getElementById("app");
document.documentElement.dataset.theme=state.theme==="dark"?"dark":"light";

const save=()=>{localStorage.setItem("lexivn_user",JSON.stringify(state.user));localStorage.setItem("lexivn_favorites",JSON.stringify(state.favorites));localStorage.setItem("lexivn_history",JSON.stringify(state.history));};
const toast=(m)=>{const e=document.getElementById("toast");e.textContent=m;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200)};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function speak(text,lang="en-US"){if(!("speechSynthesis" in window))return toast("Trình duyệt không hỗ trợ Text-to-Speech");speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang;speechSynthesis.speak(u)}
function listen(){if(!("webkitSpeechRecognition" in window)&&!("SpeechRecognition" in window))return toast("Trình duyệt chưa hỗ trợ Speech-to-Text");const R=window.SpeechRecognition||window.webkitSpeechRecognition;const r=new R();r.lang="en-US";r.interimResults=false;r.onresult=e=>{document.querySelector("#searchInput").value=e.results[0][0].transcript};r.onerror=()=>toast("Không nhận diện được giọng nói");r.start()}
function isFav(w){return state.favorites.includes(w.toLowerCase())}
function fav(w){const x=w.toLowerCase();state.favorites=isFav(x)?state.favorites.filter(v=>v!==x):[...state.favorites,x];save();toast(isFav(x)?"Đã thêm yêu thích":"Đã bỏ yêu thích");render()}
function addHistory(w){const x=w.toLowerCase();state.history=[x,...state.history.filter(v=>v!==x)].slice(0,30);save()}
function account(){const e=document.getElementById("accountArea");if(state.user)e.innerHTML=`<div class="user-chip"><span class="avatar">${esc(state.user.name?.[0]||"U").toUpperCase()}</span><button class="ghost-btn" onclick="logout()">Đăng xuất</button></div>`;else e.innerHTML=`<a class="ghost-btn" href="#login">Đăng nhập</a>`}
function logout(){state.user=null;save();location.hash="#home";toast("Đã đăng xuất")}
function setActive(){document.querySelectorAll("#main-nav a").forEach(a=>a.classList.toggle("active",location.hash===a.hash))}
async function translate(text){if(!text)return "";const key=localStorage.getItem("lexivn_gemini_key");if(key){try{const prompt=`Translate the following English dictionary text to natural Vietnamese. Return only the translation, no explanation:\\n${text}`;const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${encodeURIComponent(key)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:prompt}]}]})});const j=await r.json();const out=j?.candidates?.[0]?.content?.parts?.[0]?.text?.trim();if(out)return out}catch(e){}}
try{const r=await fetch(`https://api.mymemory.translated.net/get?q=${encodeURIComponent(text)}&langpair=en|vi`);const j=await r.json();return j?.responseData?.translatedText||""}catch(e){return ""}
}
async function lookup(word){const w=word.trim().toLowerCase();if(!w)return;location.hash="#dictionary/"+encodeURIComponent(w)}
async function renderDictionary(word){
 app.innerHTML=`<div class="container section"><div class="search-box"><input id="searchInput" value="${esc(word)}" placeholder="Nhập từ tiếng Anh..."><button class="icon-btn" onclick="listen()" title="Nói từ">🎙️</button><button class="btn" onclick="lookup(document.getElementById('searchInput').value)">Tra từ</button></div><div id="result" class="section"><div class="loading">Đang lấy dữ liệu từ điển...</div></div></div>`;
 try{
  const r=await fetch(API+encodeURIComponent(word)); if(!r.ok)throw new Error("not found"); const data=await r.json(); const d=data[0]; addHistory(word);
  const phon=d.phonetic||d.phonetics?.find(x=>x.text)?.text||"";
  let html=`<div class="result-wrap"><article class="card word-card"><div class="word-title"><div><h1>${esc(d.word)}</h1><div class="phonetic">${esc(phon)}</div></div><div class="actions"><button class="ghost-btn" onclick="speak('${esc(d.word).replace(/'/g,"\\'")}')">🔊 Phát âm</button><button class="ghost-btn" onclick="fav('${esc(d.word).replace(/'/g,"\\'")}')">${isFav(d.word)?"★ Bỏ yêu thích":"☆ Yêu thích"}</button></div></div><div id="meanings"></div></article><aside><div class="card"><h3>Từ liên quan</h3><div class="side-list">${(d.meanings||[]).slice(0,4).map(m=>`<div class="mini-word"><span>${esc(m.partOfSpeech)}</span><span>${m.definitions?.length||0} nghĩa</span></div>`).join("")}</div></div><div class="card" style="margin-top:16px"><h3>Lịch sử gần đây</h3>${state.history.slice(0,6).map(x=>`<div class="mini-word" onclick="lookup('${esc(x)}')">${esc(x)} <span>→</span></div>`).join("")||"<p class='muted'>Chưa có lịch sử.</p>"}</div></aside></div>`;
  document.getElementById("result").innerHTML=html;
  const meanings=document.getElementById("meanings");
  for(const m of (d.meanings||[])){
    const defs=m.definitions||[];
    let block=`<section class="meaning"><span class="pos">${esc(m.partOfSpeech)}</span>`;
    for(const x of defs.slice(0,6)){
      const vi=await translate(x.definition);
      const ex=x.example?await translate(x.example):"";
      block+=`<div class="definition"><strong>• ${esc(x.definition)}</strong><div class="translation">→ ${esc(vi||"Chưa có bản dịch")}</div>${x.example?`<div class="example">“${esc(x.example)}”<div class="translation">→ ${esc(ex||"Chưa có bản dịch")}</div><button class="ghost-btn small" onclick="speak('${esc(x.example).replace(/'/g,"\\'")}')">🔊 Nghe ví dụ</button></div>`:""}</div>`;
    }
    block+=`</section>`;meanings.insertAdjacentHTML("beforeend",block);
  }
 }catch(e){document.getElementById("result").innerHTML=`<div class="card empty"><h2>Không tìm thấy từ</h2><p>Hãy kiểm tra chính tả hoặc thử một từ tiếng Anh khác.</p><a class="btn" href="#home">Về trang chủ</a></div>`}
}
function home(){app.innerHTML=`<div class="container hero"><span class="eyebrow">ENGLISH → VIETNAMESE</span><h1>Hiểu từ. Hiểu ngữ cảnh.</h1><p>Tra cứu định nghĩa tiếng Anh, bản dịch tiếng Việt, ví dụ và phát âm trong một giao diện gọn gàng.</p><div class="search-box"><input id="searchInput" placeholder="Nhập từ tiếng Anh, ví dụ: beautiful"><button class="icon-btn" onclick="listen()">🎙️</button><button class="btn" onclick="lookup(document.getElementById('searchInput').value)">Tra từ</button></div></div><div class="container features"><div class="card"><div class="feature-icon">📖</div><h3>Định nghĩa</h3><p class="muted">Dữ liệu được lấy trực tiếp từ public Dictionary API.</p></div><div class="card"><div class="feature-icon">🇻🇳</div><h3>Song ngữ</h3><p class="muted">Định nghĩa và ví dụ có bản dịch tiếng Việt tự động.</p></div><div class="card"><div class="feature-icon">🔊</div><h3>Phát âm</h3><p class="muted">Nghe từ và câu ví dụ bằng Text-to-Speech.</p></div><div class="card"><div class="feature-icon">🎙️</div><h3>Nhập bằng giọng nói</h3><p class="muted">Speech-to-Text giúp tra từ nhanh hơn.</p></div></div><div class="container section"><div class="section-head"><h2>Khám phá nhanh</h2></div><div class="chips">${["hello","beautiful","computer","knowledge","dictionary","development","language","successful"].map(x=>`<button class="chip" onclick="lookup('${x}')">${x}</button>`).join("")}</div></div>`}
function favorites(){app.innerHTML=`<div class="container section"><div class="section-head"><h2>Từ yêu thích</h2><span class="muted">${state.favorites.length} từ</span></div>${state.favorites.length?`<div class="grid2">${state.favorites.map(w=>`<div class="card mini-word" onclick="lookup('${esc(w)}')"><strong>${esc(w)}</strong><span>→</span></div>`).join("")}</div>`:`<div class="card empty"><h3>Chưa có từ yêu thích</h3><p>Nhấn ☆ khi tra một từ để lưu lại.</p></div>`}</div>`}
function history(){app.innerHTML=`<div class="container section"><div class="section-head"><h2>Lịch sử tra cứu</h2><button class="btn danger" onclick="state.history=[];save();render()">Xóa lịch sử</button></div>${state.history.length?`<div class="card"><table class="table"><thead><tr><th>#</th><th>Từ</th><th>Thao tác</th></tr></thead><tbody>${state.history.map((w,i)=>`<tr><td>${i+1}</td><td><strong>${esc(w)}</strong></td><td><button class="ghost-btn" onclick="lookup('${esc(w)}')">Tra lại</button></td></tr>`).join("")}</tbody></table></div>`:`<div class="card empty">Chưa có lịch sử tra cứu.</div>`}</div>`}
function auth(mode="login"){app.innerHTML=`<div class="container"><div class="card form-card"><div class="section-head"><h2>${mode==="login"?"Đăng nhập":"Đăng ký"}</h2></div><p class="muted">Tài khoản demo được lưu cục bộ bằng localStorage trên trình duyệt.</p><form onsubmit="authSubmit(event,'${mode}')">${mode==="register"?`<div class="form-group"><label>Họ tên</label><input id="name" required></div>`:""}<div class="form-group"><label>Email</label><input id="email" type="email" required></div><div class="form-group"><label>Mật khẩu</label><input id="password" type="password" minlength="4" required></div><button class="btn" style="width:100%">${mode==="login"?"Đăng nhập":"Tạo tài khoản"}</button></form><p class="small" style="margin-top:16px">${mode==="login"?`Chưa có tài khoản? <a style="color:var(--primary)" href="#register">Đăng ký</a>`:`Đã có tài khoản? <a style="color:var(--primary)" href="#login">Đăng nhập</a>`}</p></div></div>`}
function authSubmit(e,mode){e.preventDefault();const email=document.getElementById("email").value.trim().toLowerCase(),pw=document.getElementById("password").value;const users=JSON.parse(localStorage.getItem("lexivn_users")||"[]");if(mode==="register"){if(users.some(x=>x.email===email))return toast("Email đã được đăng ký");const u={name:document.getElementById("name").value.trim(),email,pw};users.push(u);localStorage.setItem("lexivn_users",JSON.stringify(users));state.user={name:u.name,email};save();location.hash="#profile";toast("Đăng ký thành công")}else{const u=users.find(x=>x.email===email&&x.pw===pw);if(!u)return toast("Email hoặc mật khẩu không đúng");state.user={name:u.name,email:u.email};save();location.hash="#profile";toast("Đăng nhập thành công")}}
function profile(){if(!state.user)return location.hash="#login";app.innerHTML=`<div class="container section"><div class="section-head"><h2>Tài khoản</h2></div><div class="stat-grid"><div class="card stat"><span class="muted">Từ đã tra</span><strong>${state.history.length}</strong></div><div class="card stat"><span class="muted">Từ yêu thích</span><strong>${state.favorites.length}</strong></div><div class="card stat"><span class="muted">Trạng thái</span><strong>Local</strong></div></div><div class="card" style="margin-top:16px"><h3>${esc(state.user.name)}</h3><p class="muted">${esc(state.user.email)}</p><hr style="border:0;border-top:1px solid var(--line)"><h3>Cấu hình dịch AI</h3><p class="small muted">Có thể nhập Gemini API key để ưu tiên bản dịch bằng mô hình Gemini. Key chỉ được lưu trong localStorage của trình duyệt cho bản demo.</p><div class="form-group"><input id="geminiKey" type="password" placeholder="Dán Gemini API key tại đây" value="${esc(localStorage.getItem("lexivn_gemini_key")||"")}"></div><button class="btn" onclick="localStorage.setItem('lexivn_gemini_key',document.getElementById('geminiKey').value);toast('Đã lưu cấu hình')">Lưu cấu hình</button></div></div>`}
let quizIndex=0,quizScore=0;
const quizWords=["abandon","brave","curious","efficient","journey","knowledge","rapid","reliable"];
async function quiz(){const w=quizWords[quizIndex%quizWords.length];app.innerHTML=`<div class="container section"><div class="card"><div class="section-head"><h2>Luyện tập từ vựng</h2><span>Điểm: ${quizScore}</span></div><p class="muted">Chọn nghĩa tiếng Việt phù hợp với từ:</p><h1>${w}</h1><button class="ghost-btn" onclick="speak('${w}')">🔊 Nghe</button><div id="quizOptions" class="quiz-options"><div class="loading">Đang tạo câu hỏi...</div></div></div></div>`;const d=await fetch(API+w).then(r=>r.json()).catch(()=>null);const correct=d?.[0]?.meanings?.[0]?.definitions?.[0]?.definition||"";const correctVi=await translate(correct);let opts=[correctVi||"Không có bản dịch"];const pool=["rất nhanh","kiến thức và sự hiểu biết","đáng tin cậy","dũng cảm","từ bỏ hoặc rời đi","tò mò và ham tìm hiểu","hiệu quả","hành trình"];opts.push(...pool.filter(x=>!opts.includes(x)).slice(0,3));opts.sort(()=>Math.random()-.5);document.getElementById("quizOptions").innerHTML=opts.map(x=>`<button class="quiz-option" onclick="answerQuiz(this,${JSON.stringify(x)} ,${JSON.stringify(correctVi)})">${esc(x)}</button>`).join("")}
function answerQuiz(el,x,c){document.querySelectorAll(".quiz-option").forEach(b=>b.disabled=true);if(x===c){el.classList.add("correct");quizScore++;toast("Chính xác!")}else{el.classList.add("wrong");toast("Chưa chính xác")}setTimeout(()=>{quizIndex++;quiz()},800)}
function settings(){profile()}
function render(){account();setActive();const h=location.hash.slice(1)||"home";if(h.startsWith("dictionary/"))renderDictionary(decodeURIComponent(h.split("/").slice(1).join("/")));else if(h==="home")home();else if(h==="favorites")favorites();else if(h==="history")history();else if(h==="login")auth("login");else if(h==="register")auth("register");else if(h==="profile")profile();else if(h==="quiz")quiz();else home()}
document.getElementById("themeBtn").onclick=()=>{state.theme=state.theme==="dark"?"light":"dark";localStorage.setItem("lexivn_theme",state.theme);document.documentElement.dataset.theme=state.theme};
window.addEventListener("hashchange",render);window.lookup=lookup;window.listen=listen;window.speak=speak;window.fav=fav;window.logout=logout;window.render=render;window.authSubmit=authSubmit;window.answerQuiz=answerQuiz;render();
